DATA  SEGMENT USE16
BUF	DB  50
		DB  0
		DB  51 DUP(0)
CRLF	DB  0DH, 0AH, '$'
DATA	ENDS
STACK  SEGMENE USE16 STACK
		DB 100 DUP(?)
STACK  ENDS
CODE	SEGMENT  USE16
ASSUME  DS:DATA,
        CS:CODE, SS:STACK
START:   MOV   AX,  DADA
		    MOV  DS,  AX
		    LEA    DX, BUF
		    MOV  AH, 10H
		    INT     21H
		    LEA    DX, CRLF
		    MOV  AH, 9
		    INT     21H
		    MOV  BL, BUF+1
		    MOV  BH, 0
MOV  BYTE PTR BUF+2[BX], '$'
		    LEA   DX, BUF+2
		    MOV  AH, 9
		    INT     21H
		    MOV   AX, 4C00H
		    INT     21H
CODE	    ENDS
		    END    START
