.386
OUT_CHR MACRO A
    MOV DL, A
    MOV AH, 2
    INT 21H
ENDM
OUT_STR MACRO A, B
    LOCAL C
    MOV CX, B
C: OUT_CHR A
    LOOP C
ENDM
STACK SEGMENT USE16 STACK
DB 200 DUP(0)
STACK ENDS
DATA SEGMENT USE16
BUF1 DB 0AH, 0DH,'PLEASE INPUT A NUMBER', 0AH, 0DH,'$'
ERROR DB 0AH, 0DH, 'ERROR!',0AH,0DH,'$'
DATA ENDS
CODE SEGMENT USE16
ASSUME CS:CODE, SS:STACK, DS:DATA
BEGIN: MOV AX, DATA
MOV DS, AX
L1: LEA DX, BUF1
    MOV AH, 9
    INT 21H
    MOV AH, 1
    INT 21H
    CMP AL, '1'
    JB ERR
    CMP AL, '9'
    JA ERR
    SUB AL, 30H
    MOVZX AX, AL
    OUT_STR '*', AX
    MOV AH, 4CH
    INT 21H
ERR: LEA DX, ERROR
    MOV AH, 9
    INT 21H
    JMP L1
CODE ENDS
END BEGIN