CREATE TABLE S(
    SNO CHAR(10) UNIQUE,
    SNAME VARCHAR(20),
    STATUS INT,
    CITY VARCHAR(10)
);

CREATE TABLE P(
    PNO CHAR(10) UNIQUE,
    PNAME VARCHAR(20),
    COLOR CHAR(5),
    WEIGHT INT
);

CREATE TABLE J(
    JNO CHAR(10) UNIQUE,
    JNAME VARCHAR(20),
    CITY VARCHAR(10)
);

CREATE TABLE SPJ(
    SNO CHAR(5),
    PNO CHAR(5),
    JNO CHAR(5),
    QTY INT
);