-- 1
SELECT DISTINCT SNO FROM SPJ WHERE JNO = 'J1';
-- 2
SELECT DISTINCT SNO FROM SPJ WHERE JNO = 'J1' AND PNO='P1';
-- 3
SELECT DISTINCT SNO FROM SPJ WHERE JNO = 'J1' AND PNO IN (SELECT PNO FROM  P WHERE COLOR = '红');
-- 3
SELECT DISTINCT SNO FROM SPJ,P WHERE SPJ.JNO = 'J1' AND SPJ.PNO = P.PNO AND P.COLOR = '红';
-- 4
SELECT DISTINCT JNO FROM SPJ WHERE JNO NOT IN (SELECT DISTINCT JNO FROM SPJ,P,J
    WHERE SPJ.PNO = P.PNO AND SPJ.JNO = J.JNO AND P.COLOR = '红' AND J.CITY = '天津')
-- 5
-- 分布查询
SELECT DISTINCT JNO FROM SPJ WHERE SNO='S1'

SELECT JNO FROM SPJ WHERE PNO = 'P1' AND JNO IN (SELECT JNO FROM SPJ WHERE PNO = 'P2');

-- 第五题

SELECT SNAME,CITY FROM S;

SELECT PNAME,COLOR,WEIGHT FROM P;

SELECT DISTINCT JNO FROM SPJ WHERE SNO='S1'

SELECT PNAME,QTY FROM SPJ,P WHERE
     P.PNO = SPJ.PNO AND SPJ.JON = 'J2'

SELECT PNO FROM SPJ,S WHERE S.SNO = SPJ.SNO AND CITY = '上海';

SELECT JNAME FROM SPJ,S,J 
    WHERE S.SNO = SPJ.SNO AND S.CITY = '上海' AND J.JNO = SPJ.JNO;

SELECT DISTINCT JNO FROM SPJ,S WHERE JNO 
    NOT IN (
        SELECT DISTINCT JNO FROM SPJ,S WHERE S.SNO=SPJ.SNO AND 
            S.CITY = '天津'
    );

UPDATE P SET COLOR = '蓝' 
    WHERE COLOR = '红'
UPDATE SPJ SET SNO = 'S3' WHERE SNO='S5' AND JNO = 'J4' AND PNO = 'P6';

DELETE FROM S WHERE SNO = 'S2'
DELETE FROM SPJ WHERE SNO = 'S2'

INSERT INTO SPJ VALUES('S2','J6','P4',200);

GRANT ALL PRIVILEGES ON  '学生','班级'
TO U1;

GRANT SELECT,UPDATE('家庭住址'),DELETE ON '学生' TO U2;

GRANT SELECT ON '班级' TO PUBLIC;

GRANT UPDATE,SELECT ON '班级' TO R1;

GRANT R1 TO U1 WITH ADMIN OPTION;

GRANT SELECT ON '职工','部门'
TO '王明';

GRANT INSERT,DELETE ON '职工','部门'
TO '李勇'

GRANT SELECT ON 职工
WHEN USER() = NAME;
TO ALL;

GRANT SELECT,UPDATE('工资') ON 职工
TO '刘星'

GRANT ALTER TABLE ON '职工','部门'
TO '张新'

GRANT ALL PRIVILIGES ON '职工','部门'
TO '周平' WITH GRANT OPTION;

CREATE VIEW 部门工资 AS
SELECT 部门,名称,MAX(工资),MIN(工资),AVG(工资) FROM 
    职工,部门
    WHERE 职工.部门号=部门.部门号
    GROUP BY 职工.部门号
GRANT SELECT ON 部门工资
